color0       #020000
color8       #A29063
color1       #62512A
color9       #62512A
color2       #69562A
color10      #69562A
color3       #98772C
color11      #98772C
color4       #A17E2C
color12      #A17E2C
color5       #D7A42E
color13      #D7A42E
color6       #E2AC2E
color14      #E2AC2E
color7       #E8CD8E
color15      #E8CD8E