# -----------------------------------------------------
# General window layout and colors
# name: "Default"
# -----------------------------------------------------

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgb(215,153,33)
    col.inactive_border = rgb(42,41,41)
    layout = dwindle
    resize_on_border = true
}
