$image = /home/krazi/walls/architecture/a_city_skyline_with_a_tall_building.jpg

$background = rgba(1a120eff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(382e2aff)

$inverse_primary = rgba(974720ff)

$inverse_surface = rgba(f0dfd9ff)

$on_background = rgba(f0dfd9ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(581e00ff)

$on_primary_container = rgba(330e00ff)

$on_primary_fixed = rgba(360f00ff)

$on_primary_fixed_variant = rgba(79310aff)

$on_secondary = rgba(4a2717ff)

$on_secondary_container = rgba(ffddd0ff)

$on_secondary_fixed = rgba(311305ff)

$on_secondary_fixed_variant = rgba(643d2bff)

$on_surface = rgba(f0dfd9ff)

$on_surface_variant = rgba(dbc1b7ff)

$on_tertiary = rgba(333200ff)

$on_tertiary_container = rgba(1b1b00ff)

$on_tertiary_fixed = rgba(1d1d00ff)

$on_tertiary_fixed_variant = rgba(4a4900ff)

$outline = rgba(a38c83ff)

$outline_variant = rgba(55433bff)

$primary = rgba(ffb596ff)

$primary_container = rgba(ee8b5eff)

$primary_fixed = rgba(ffdbcdff)

$primary_fixed_dim = rgba(ffb596ff)

$scrim = rgba(000000ff)

$secondary = rgba(f3baa2ff)

$secondary_container = rgba(673f2dff)

$secondary_fixed = rgba(ffdbcdff)

$secondary_fixed_dim = rgba(f3baa2ff)

$shadow = rgba(000000ff)

$source_color = rgba(ee8b5eff)

$surface = rgba(1a120eff)

$surface_bright = rgba(413733ff)

$surface_container = rgba(261e1aff)

$surface_container_high = rgba(312824ff)

$surface_container_highest = rgba(3d332fff)

$surface_container_low = rgba(221a16ff)

$surface_container_lowest = rgba(140c09ff)

$surface_dim = rgba(1a120eff)

$surface_tint = rgba(ffb596ff)

$surface_variant = rgba(55433bff)

$tertiary = rgba(cecb5bff)

$tertiary_container = rgba(aba93dff)

$tertiary_fixed = rgba(eae874ff)

$tertiary_fixed_dim = rgba(cecb5bff)

