$image = /home/stocki/Documents/inkscape projet/banner.png

$background = rgba(171215ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(352f33ff)

$inverse_primary = rgba(85497cff)

$inverse_surface = rgba(ebe0e5ff)

$on_background = rgba(ebe0e5ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(501b4bff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(370335ff)

$on_primary_fixed_variant = rgba(6a3263ff)

$on_secondary = rgba(41283cff)

$on_secondary_container = rgba(fad5f0ff)

$on_secondary_fixed = rgba(2a1427ff)

$on_secondary_fixed_variant = rgba(593e53ff)

$on_surface = rgba(ebe0e5ff)

$on_surface_variant = rgba(d3c2ccff)

$on_tertiary = rgba(5a1a1cff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(3e0409ff)

$on_tertiary_fixed_variant = rgba(772f30ff)

$outline = rgba(9b8d96ff)

$outline_variant = rgba(4f434bff)

$primary = rgba(f7b0eaff)

$primary_container = rgba(bd7bb1ff)

$primary_fixed = rgba(ffd7f4ff)

$primary_fixed_dim = rgba(f7b0eaff)

$scrim = rgba(000000ff)

$secondary = rgba(e0bcd6ff)

$secondary_container = rgba(593e53ff)

$secondary_fixed = rgba(fdd8f2ff)

$secondary_fixed_dim = rgba(e0bcd6ff)

$shadow = rgba(000000ff)

$source_color = rgba(a5669bff)

$surface = rgba(171215ff)

$surface_bright = rgba(3e373bff)

$surface_container = rgba(231e22ff)

$surface_container_high = rgba(2e282cff)

$surface_container_highest = rgba(393337ff)

$surface_container_low = rgba(1f1a1eff)

$surface_container_lowest = rgba(110d10ff)

$surface_dim = rgba(171215ff)

$surface_tint = rgba(f7b0eaff)

$surface_variant = rgba(4f434bff)

$tertiary = rgba(ffb3b1ff)

$tertiary_container = rgba(d27775ff)

$tertiary_fixed = rgba(ffdad8ff)

$tertiary_fixed_dim = rgba(ffb3b1ff)

