$image = /home/stocki/Documents/inkscape projet/2026 house wallpaper 3.png

$background = rgba(171309ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(353024ff)

$inverse_primary = rgba(735c00ff)

$inverse_surface = rgba(ebe2d0ff)

$on_background = rgba(ebe2d0ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(3c2f00ff)

$on_primary_container = rgba(4b3b00ff)

$on_primary_fixed = rgba(231b00ff)

$on_primary_fixed_variant = rgba(574500ff)

$on_secondary = rgba(3c2f00ff)

$on_secondary_container = rgba(fde295ff)

$on_secondary_fixed = rgba(231b00ff)

$on_secondary_fixed_variant = rgba(564505ff)

$on_surface = rgba(ebe2d0ff)

$on_surface_variant = rgba(d1c6abff)

$on_tertiary = rgba(293500ff)

$on_tertiary_container = rgba(344200ff)

$on_tertiary_fixed = rgba(171e00ff)

$on_tertiary_fixed_variant = rgba(3d4d00ff)

$outline = rgba(9a9078ff)

$outline_variant = rgba(4e4632ff)

$primary = rgba(ffebb8ff)

$primary_container = rgba(fbcb02ff)

$primary_fixed = rgba(ffe086ff)

$primary_fixed_dim = rgba(efc100ff)

$scrim = rgba(000000ff)

$secondary = rgba(dec47aff)

$secondary_container = rgba(594707ff)

$secondary_fixed = rgba(fce093ff)

$secondary_fixed_dim = rgba(dec47aff)

$shadow = rgba(000000ff)

$source_color = rgba(fbcb02ff)

$surface = rgba(171309ff)

$surface_bright = rgba(3e392cff)

$surface_container = rgba(231f14ff)

$surface_container_high = rgba(2e2a1eff)

$surface_container_highest = rgba(393428ff)

$surface_container_low = rgba(1f1b10ff)

$surface_container_lowest = rgba(110e05ff)

$surface_dim = rgba(171309ff)

$surface_tint = rgba(efc100ff)

$surface_variant = rgba(4e4632ff)

$tertiary = rgba(d8fb65ff)

$tertiary_container = rgba(bcde4bff)

$tertiary_fixed = rgba(cdf05bff)

$tertiary_fixed_dim = rgba(b2d341ff)

