-- Generated by nwg-displays on 2026-09-30 at 18:08:30. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2048x1152@60.0",
    position = "0x0",
    scale = 1.0,
    bitdepth = 10,
    vrr = 0
})
